services:
  frontend:
    build:
      context: C:\Users\DIEID\Desktop\fiscalia\frontend
    container_name: react-app
    command: npm run dev -- --host
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - "3000:3000"
    environment:
      - VITE_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - VITE_BASE_API_URL=http://web:8000
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
