services:
  frontend:
    build:
      context: C:\Users\DIEID\Desktop\fiscalia\frontend
    container_name: react-app
    command: npm run dev
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules:/frontend/node_modules
    ports:
      - "3000:3000"
